version: '3.8'

services:
  client:
    build: ./front
    container_name: client_frontend
    ports:
      - '3000:3000' 
    volumes:
      - .:/app
  # - ./app/node_modules
    stdin_open: true
    tty: true
  backend:
    build: ./back
    container_name: client_backend
    ports:
      - '8001:80' 
    volumes:
      - .:/app
